"""Generate the reviewed D1 schema migration from the reference SQLAlchemy models.

This is a development-time tool. The Worker executes the checked-in SQL file,
never imports SQLAlchemy or the PostgreSQL backend at runtime.
"""

from __future__ import annotations

import os
from pathlib import Path
import sys

from sqlalchemy import Boolean, CheckConstraint, Date, DateTime, Integer, JSON, MetaData, Numeric, Text, Time
from sqlalchemy.schema import CreateIndex, CreateTable
from sqlalchemy.dialects import sqlite


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))
os.environ["DATABASE_URL"] = "sqlite://"

from app.db import Base  # noqa: E402
import app.models  # noqa: E402,F401


VERSION = "0002_school_schema"
MODEL_TABLES = frozenset(Base.metadata.tables)
MONEY_COLUMNS: dict[str, tuple[str, ...]] = {}
DECIMAL_COLUMNS: dict[str, tuple[str, ...]] = {}


def schema_sql() -> str:
    metadata = MetaData()
    for table in Base.metadata.sorted_tables:
        table.to_metadata(metadata)

    money: dict[str, list[str]] = {}
    decimals: dict[str, list[str]] = {}
    for table in metadata.tables.values():
        for column in table.columns:
            kind = column.type
            if isinstance(kind, Numeric):
                if kind.scale != 2:
                    raise ValueError(f"Unsupported decimal scale: {table.name}.{column.name}")
                bucket = money if kind.precision == 12 else decimals
                if kind.precision not in (5, 7, 12):
                    raise ValueError(f"Unreviewed numeric precision: {table.name}.{column.name}")
                bucket.setdefault(table.name, []).append(column.name)
                column.type = Integer()
                nullable = f"{column.name} IS NULL OR " if column.nullable else ""
                table.append_constraint(CheckConstraint(
                    f"{nullable}typeof({column.name}) = 'integer'",
                    name=f"{column.name}_scaled_integer",
                ))
            elif isinstance(kind, (Date, DateTime, Time, JSON)):
                column.type = Text()
            elif isinstance(kind, Boolean):
                column.type = Integer()

    MONEY_COLUMNS.update({name: tuple(cols) for name, cols in money.items()})
    DECIMAL_COLUMNS.update({name: tuple(cols) for name, cols in decimals.items()})

    statements = [
        "-- Generated by generate_school_schema.py from backend/app/models.py.",
        "-- No production data exists in the 0001 probe schema. Abort if it is nonempty.",
        "-- All NUMERIC(12,2) columns store integer INR paise; other NUMERIC(*,2)",
        "-- columns store integer hundredths of their academic value.",
        "-- Dates are ISO 8601 text; timestamps are UTC ISO 8601 text; JSON is text.",
        "CREATE TABLE _school_schema_empty_guard (zero INTEGER NOT NULL CHECK (zero = 0));",
        "INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM tenants;",
        "INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM users;",
        "INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM auth_sessions;",
        "DROP TABLE _school_schema_empty_guard;",
        "DROP TABLE auth_sessions;",
        "DROP TABLE users;",
        "DROP TABLE tenants;",
    ]
    dialect = sqlite.dialect()
    for table in metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=dialect)).strip()
        lines = ddl.splitlines()
        clauses = [line.strip().rstrip(", ") for line in lines[1:-1]]
        constraint_prefixes = ("PRIMARY KEY", "FOREIGN KEY", "UNIQUE", "CONSTRAINT", "CHECK")
        columns = [line for line in clauses if not line.startswith(constraint_prefixes)]
        constraints = sorted(line for line in clauses if line.startswith(constraint_prefixes))
        statements.append(lines[0] + "\n\t" + ",\n\t".join(columns + constraints) + "\n);")
    for table in metadata.sorted_tables:
        for index in sorted(table.indexes, key=lambda item: item.name or ""):
            statements.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
    statements.append(
        "INSERT INTO schema_versions (version, applied_at) "
        f"VALUES ('{VERSION}', CURRENT_TIMESTAMP);"
    )
    return "\n\n".join(statements) + "\n"


def main() -> None:
    output = ROOT / "cloudflare" / "worker" / "migrations" / f"{VERSION}.sql"
    output.write_text(schema_sql(), encoding="utf-8")
    print(f"Wrote {output} ({len(MODEL_TABLES)} tables)")


if __name__ == "__main__":
    main()
