name = "school-api-finance-staging"
main = "src/finance_entry.py"
compatibility_date = "2024-09-23"
compatibility_flags = ["python_workers"]
account_id = "24e366c9448ef4c466bffe6f17efa51b"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "school-staging-d1"
database_id = "e27122b3-e2ba-474f-b7b3-dc7cddd39a89"
migrations_dir = "migrations"
