-- Generated by generate_school_schema.py from backend/app/models.py.

-- No production data exists in the 0001 probe schema. Abort if it is nonempty.

-- All NUMERIC(12,2) columns store integer INR paise; other NUMERIC(*,2)

-- columns store integer hundredths of their academic value.

-- Dates are ISO 8601 text; timestamps are UTC ISO 8601 text; JSON is text.

CREATE TABLE _school_schema_empty_guard (zero INTEGER NOT NULL CHECK (zero = 0));

INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM tenants;

INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM users;

INSERT INTO _school_schema_empty_guard SELECT COUNT(*) FROM auth_sessions;

DROP TABLE _school_schema_empty_guard;

DROP TABLE auth_sessions;

DROP TABLE users;

DROP TABLE tenants;

CREATE TABLE tenants (
	id VARCHAR(64) NOT NULL,
	name VARCHAR(200) NOT NULL,
	active INTEGER NOT NULL,
	city VARCHAR(120) NOT NULL,
	board VARCHAR(120) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE academic_years (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	year VARCHAR(9) NOT NULL,
	start_date TEXT NOT NULL,
	end_date TEXT NOT NULL,
	status VARCHAR(16) NOT NULL,
	grade_bands TEXT,
	pass_percentage INTEGER,
	exam_order TEXT,
	CONSTRAINT pass_percentage_scaled_integer CHECK (pass_percentage IS NULL OR typeof(pass_percentage) = 'integer'),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, year)
);

CREATE TABLE class_subjects (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	subject_name VARCHAR(120) NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, class_name, academic_year, subject_name)
);

CREATE TABLE contact_enquiries (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	name VARCHAR(200) NOT NULL,
	email VARCHAR(320) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	grade_interested VARCHAR(80) NOT NULL,
	message VARCHAR(4000) NOT NULL,
	created_at TEXT NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE exam_configs (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	exam_type VARCHAR(80) NOT NULL,
	display_name VARCHAR(120) NOT NULL,
	weightage_percent INTEGER NOT NULL,
	max_marks_default INTEGER NOT NULL,
	is_active INTEGER NOT NULL,
	CONSTRAINT exam_max_marks_positive CHECK (max_marks_default > 0),
	CONSTRAINT exam_weightage_range CHECK (weightage_percent >= 0 AND weightage_percent <= 100),
	CONSTRAINT max_marks_default_scaled_integer CHECK (typeof(max_marks_default) = 'integer'),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, academic_year, exam_type)
);

CREATE TABLE expenses (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	title VARCHAR(200) NOT NULL,
	category VARCHAR(120) NOT NULL,
	amount INTEGER NOT NULL,
	date TEXT NOT NULL,
	paid_to VARCHAR(200) NOT NULL,
	remarks VARCHAR(1000),
	created_at TEXT NOT NULL,
	voided_at TEXT,
	CONSTRAINT amount_scaled_integer CHECK (typeof(amount) = 'integer'),
	CONSTRAINT expense_amount_positive CHECK (amount > 0),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE fee_structures (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, class_name, academic_year)
);

CREATE TABLE rollover_runs (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	idempotency_key VARCHAR(128) NOT NULL,
	request_fingerprint VARCHAR(64) NOT NULL,
	source_class VARCHAR(80) NOT NULL,
	source_year VARCHAR(9) NOT NULL,
	target_class VARCHAR(80),
	target_year VARCHAR(9),
	student_count INTEGER NOT NULL,
	student_ids TEXT NOT NULL,
	created_at TEXT NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE school_classes (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	base_class VARCHAR(80) NOT NULL,
	section VARCHAR(16) NOT NULL,
	sort_order INTEGER NOT NULL,
	active INTEGER NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, class_name)
);

CREATE TABLE school_site_content (
	tenant_id VARCHAR(64) NOT NULL,
	content TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (tenant_id)
);

CREATE TABLE school_subjects (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	name VARCHAR(120) NOT NULL,
	sort_order INTEGER NOT NULL,
	active INTEGER NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, name)
);

CREATE TABLE staff (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	employee_id VARCHAR(64) NOT NULL,
	full_name VARCHAR(200) NOT NULL,
	email VARCHAR(320) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	department VARCHAR(80) NOT NULL,
	designation VARCHAR(120) NOT NULL,
	date_of_joining TEXT NOT NULL,
	date_of_leaving TEXT,
	basic_salary INTEGER NOT NULL,
	status VARCHAR(24) NOT NULL,
	details TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT,
	deleted_at TEXT,
	CONSTRAINT basic_salary_scaled_integer CHECK (typeof(basic_salary) = 'integer'),
	CONSTRAINT staff_salary_nonnegative CHECK (basic_salary >= 0),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, employee_id)
);

CREATE TABLE students (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	full_name VARCHAR(200) NOT NULL,
	date_of_birth TEXT NOT NULL,
	gender VARCHAR(32) NOT NULL,
	blood_group VARCHAR(16) NOT NULL,
	nationality VARCHAR(80) NOT NULL,
	religion VARCHAR(80) NOT NULL,
	mother_tongue VARCHAR(80) NOT NULL,
	aadhar_number VARCHAR(32) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	date_of_admission TEXT NOT NULL,
	admission_number VARCHAR(64),
	roll_number VARCHAR(32),
	status VARCHAR(16) NOT NULL,
	parent_details TEXT NOT NULL,
	contact_details TEXT NOT NULL,
	previous_school_details TEXT NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, admission_number)
);

CREATE TABLE timetable_days (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	day_of_week VARCHAR(16) NOT NULL,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, class_name, academic_year, day_of_week)
);

CREATE TABLE transport_routes (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	zone_name VARCHAR(120) NOT NULL,
	display_name VARCHAR(200) NOT NULL,
	areas_covered VARCHAR(1000) NOT NULL,
	stops TEXT NOT NULL,
	first_pickup_time VARCHAR(40) NOT NULL,
	monthly_fee INTEGER NOT NULL,
	created_at TEXT NOT NULL,
	deleted_at TEXT,
	CONSTRAINT monthly_fee_scaled_integer CHECK (typeof(monthly_fee) = 'integer'),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, zone_name)
);

CREATE TABLE users (
	id VARCHAR(36) NOT NULL,
	scope VARCHAR(64) NOT NULL,
	tenant_id VARCHAR(64),
	email VARCHAR(320) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	full_name VARCHAR(200) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	role VARCHAR(40) NOT NULL,
	linked_entity_id VARCHAR(36),
	extra_permissions TEXT NOT NULL,
	active INTEGER NOT NULL,
	created_at TEXT NOT NULL,
	last_login_at TEXT,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (scope, email)
);

CREATE TABLE ai_configs (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	enabled INTEGER NOT NULL,
	enabled_modes TEXT NOT NULL,
	primary_provider VARCHAR(32) NOT NULL,
	ollama_base_url VARCHAR(500) NOT NULL,
	ollama_model VARCHAR(120) NOT NULL,
	daily_limit_per_student INTEGER NOT NULL,
	max_conversation_turns INTEGER NOT NULL,
	updated_by VARCHAR(36),
	updated_at TEXT,
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	FOREIGN KEY(updated_by) REFERENCES users (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id)
);

CREATE TABLE auth_sessions (
	id VARCHAR(36) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	access_hash VARCHAR(64) NOT NULL,
	refresh_hash VARCHAR(64) NOT NULL,
	access_expires_at TEXT NOT NULL,
	refresh_expires_at TEXT NOT NULL,
	revoked_at TEXT,
	FOREIGN KEY(user_id) REFERENCES users (id),
	PRIMARY KEY (id),
	UNIQUE (access_hash),
	UNIQUE (refresh_hash)
);

CREATE TABLE buses (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	bus_number VARCHAR(80) NOT NULL,
	driver_name VARCHAR(200) NOT NULL,
	driver_mobile VARCHAR(40) NOT NULL,
	route_id VARCHAR(36),
	capacity INTEGER NOT NULL,
	status VARCHAR(16) NOT NULL,
	insurance_expiry VARCHAR(40),
	notes VARCHAR(1000),
	created_at TEXT NOT NULL,
	deleted_at TEXT,
	CONSTRAINT bus_capacity_positive CHECK (capacity > 0),
	FOREIGN KEY(route_id) REFERENCES transport_routes (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, bus_number)
);

CREATE TABLE certificate_records (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	student_id VARCHAR(36) NOT NULL,
	student_name VARCHAR(200) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	certificate_type VARCHAR(24) NOT NULL,
	serial_number VARCHAR(80) NOT NULL,
	reason VARCHAR(1000) NOT NULL,
	additional_fields TEXT NOT NULL,
	generated_by VARCHAR(200) NOT NULL,
	generated_at TEXT NOT NULL,
	FOREIGN KEY(student_id) REFERENCES students (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, serial_number)
);

CREATE TABLE chat_rooms (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	participant_1_id VARCHAR(36) NOT NULL,
	participant_2_id VARCHAR(36) NOT NULL,
	student_key VARCHAR(36) NOT NULL,
	created_at TEXT NOT NULL,
	FOREIGN KEY(participant_1_id) REFERENCES users (id),
	FOREIGN KEY(participant_2_id) REFERENCES users (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, participant_1_id, participant_2_id, student_key)
);

CREATE TABLE class_year_closures (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	rollover_run_id VARCHAR(36) NOT NULL,
	closed_at TEXT NOT NULL,
	FOREIGN KEY(rollover_run_id) REFERENCES rollover_runs (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, class_name, academic_year)
);

CREATE TABLE enrollments (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	student_id VARCHAR(36) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	roll_number VARCHAR(32),
	date_of_admission TEXT NOT NULL,
	status VARCHAR(16) NOT NULL,
	FOREIGN KEY(student_id) REFERENCES students (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, student_id, academic_year)
);

CREATE TABLE fee_components (
	id VARCHAR(36) NOT NULL,
	structure_id VARCHAR(36) NOT NULL,
	position INTEGER NOT NULL,
	name VARCHAR(120) NOT NULL,
	amount INTEGER NOT NULL,
	frequency VARCHAR(16) NOT NULL,
	description VARCHAR(500) NOT NULL,
	CONSTRAINT amount_scaled_integer CHECK (typeof(amount) = 'integer'),
	CONSTRAINT fee_component_amount_positive CHECK (amount > 0),
	FOREIGN KEY(structure_id) REFERENCES fee_structures (id),
	PRIMARY KEY (id),
	UNIQUE (structure_id, name)
);

CREATE TABLE homework (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	title VARCHAR(200) NOT NULL,
	description VARCHAR(4000) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	subject VARCHAR(120) NOT NULL,
	teacher_id VARCHAR(36) NOT NULL,
	teacher_name VARCHAR(200) NOT NULL,
	due_date TEXT NOT NULL,
	assigned_date TEXT NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	status VARCHAR(16) NOT NULL,
	created_at TEXT NOT NULL,
	deleted_at TEXT,
	FOREIGN KEY(teacher_id) REFERENCES users (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE incidents (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	student_id VARCHAR(36) NOT NULL,
	student_name VARCHAR(200) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	severity VARCHAR(16) NOT NULL,
	category VARCHAR(32) NOT NULL,
	description VARCHAR(4000) NOT NULL,
	action_taken VARCHAR(2000) NOT NULL,
	reported_by VARCHAR(200) NOT NULL,
	incident_date TEXT NOT NULL,
	parent_notified INTEGER NOT NULL,
	parent_notified_at TEXT,
	follow_up_notes VARCHAR(2000) NOT NULL,
	resolved INTEGER NOT NULL,
	resolved_at TEXT,
	created_at TEXT NOT NULL,
	FOREIGN KEY(student_id) REFERENCES students (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE leave_requests (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	staff_id VARCHAR(36) NOT NULL,
	staff_name VARCHAR(200) NOT NULL,
	department VARCHAR(80) NOT NULL,
	leave_type VARCHAR(32) NOT NULL,
	from_date TEXT NOT NULL,
	to_date TEXT NOT NULL,
	total_days INTEGER NOT NULL,
	reason VARCHAR(1000) NOT NULL,
	status VARCHAR(16) NOT NULL,
	approved_by VARCHAR(200),
	approver_remarks VARCHAR(1000),
	approved_at TEXT,
	applied_at TEXT NOT NULL,
	FOREIGN KEY(staff_id) REFERENCES staff (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE notifications (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	title VARCHAR(200) NOT NULL,
	message VARCHAR(4000) NOT NULL,
	type VARCHAR(32) NOT NULL,
	target_audience VARCHAR(24) NOT NULL,
	target_class VARCHAR(80),
	target_student_id VARCHAR(36),
	priority VARCHAR(16) NOT NULL,
	created_by VARCHAR(200) NOT NULL,
	creator_id VARCHAR(36) NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT,
	deleted_at TEXT,
	FOREIGN KEY(creator_id) REFERENCES users (id),
	FOREIGN KEY(target_student_id) REFERENCES students (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE salary_records (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	staff_id VARCHAR(36) NOT NULL,
	staff_name VARCHAR(200) NOT NULL,
	department VARCHAR(80) NOT NULL,
	designation VARCHAR(120) NOT NULL,
	month INTEGER NOT NULL,
	year INTEGER NOT NULL,
	basic_pay INTEGER NOT NULL,
	hra INTEGER NOT NULL,
	da INTEGER NOT NULL,
	ta INTEGER NOT NULL,
	other_allowances INTEGER NOT NULL,
	pf INTEGER NOT NULL,
	tax INTEGER NOT NULL,
	other_deductions INTEGER NOT NULL,
	gross_salary INTEGER NOT NULL,
	total_deductions INTEGER NOT NULL,
	net_salary INTEGER NOT NULL,
	status VARCHAR(16) NOT NULL,
	payment_mode VARCHAR(32),
	transaction_ref VARCHAR(120),
	generated_by VARCHAR(200) NOT NULL,
	generated_at TEXT NOT NULL,
	paid_at TEXT,
	CONSTRAINT basic_pay_scaled_integer CHECK (typeof(basic_pay) = 'integer'),
	CONSTRAINT da_scaled_integer CHECK (typeof(da) = 'integer'),
	CONSTRAINT gross_salary_scaled_integer CHECK (typeof(gross_salary) = 'integer'),
	CONSTRAINT hra_scaled_integer CHECK (typeof(hra) = 'integer'),
	CONSTRAINT net_salary_scaled_integer CHECK (typeof(net_salary) = 'integer'),
	CONSTRAINT other_allowances_scaled_integer CHECK (typeof(other_allowances) = 'integer'),
	CONSTRAINT other_deductions_scaled_integer CHECK (typeof(other_deductions) = 'integer'),
	CONSTRAINT pf_scaled_integer CHECK (typeof(pf) = 'integer'),
	CONSTRAINT salary_month_range CHECK (month >= 1 AND month <= 12),
	CONSTRAINT ta_scaled_integer CHECK (typeof(ta) = 'integer'),
	CONSTRAINT tax_scaled_integer CHECK (typeof(tax) = 'integer'),
	CONSTRAINT total_deductions_scaled_integer CHECK (typeof(total_deductions) = 'integer'),
	FOREIGN KEY(staff_id) REFERENCES staff (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, staff_id, month, year)
);

CREATE TABLE staff_attendance (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	staff_id VARCHAR(36) NOT NULL,
	staff_name VARCHAR(200) NOT NULL,
	department VARCHAR(80) NOT NULL,
	date TEXT NOT NULL,
	status VARCHAR(16) NOT NULL,
	check_in_time VARCHAR(5),
	check_out_time VARCHAR(5),
	remarks VARCHAR(1000) NOT NULL,
	marked_by VARCHAR(200) NOT NULL,
	marked_at TEXT NOT NULL,
	FOREIGN KEY(staff_id) REFERENCES staff (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, staff_id, date)
);

CREATE TABLE timetable_periods (
	id VARCHAR(36) NOT NULL,
	day_id VARCHAR(36) NOT NULL,
	period_number INTEGER NOT NULL,
	subject VARCHAR(120) NOT NULL,
	teacher_name VARCHAR(200) NOT NULL,
	start_time TEXT NOT NULL,
	end_time TEXT NOT NULL,
	CONSTRAINT timetable_period_number_positive CHECK (period_number > 0),
	CONSTRAINT timetable_time_order CHECK (start_time < end_time),
	FOREIGN KEY(day_id) REFERENCES timetable_days (id) ON DELETE CASCADE,
	PRIMARY KEY (id),
	UNIQUE (day_id, period_number)
);

CREATE TABLE tutorial_videos (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	title VARCHAR(200) NOT NULL,
	description VARCHAR(4000) NOT NULL,
	subject VARCHAR(120) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	academic_year VARCHAR(9) NOT NULL,
	chapter VARCHAR(200) NOT NULL,
	teacher_id VARCHAR(36) NOT NULL,
	teacher_name VARCHAR(200) NOT NULL,
	storage_key VARCHAR(80) NOT NULL,
	file_name VARCHAR(255) NOT NULL,
	content_type VARCHAR(80) NOT NULL,
	file_size BIGINT NOT NULL,
	status VARCHAR(16) NOT NULL,
	created_at TEXT NOT NULL,
	deleted_at TEXT,
	FOREIGN KEY(teacher_id) REFERENCES users (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, storage_key)
);

CREATE TABLE ai_conversations (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	homework_id VARCHAR(36),
	mode VARCHAR(16) NOT NULL,
	subject VARCHAR(120) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	messages TEXT NOT NULL,
	session_active INTEGER NOT NULL,
	total_input_tokens INTEGER NOT NULL,
	total_output_tokens INTEGER NOT NULL,
	created_at TEXT NOT NULL,
	last_message_at TEXT,
	FOREIGN KEY(homework_id) REFERENCES homework (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	PRIMARY KEY (id)
);

CREATE TABLE attendance (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	enrollment_id VARCHAR(36) NOT NULL,
	date TEXT NOT NULL,
	status VARCHAR(16) NOT NULL,
	marked_by VARCHAR(200) NOT NULL,
	remarks VARCHAR(1000) NOT NULL,
	updated_at TEXT NOT NULL,
	voided_at TEXT,
	FOREIGN KEY(enrollment_id) REFERENCES enrollments (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, enrollment_id, date)
);

CREATE TABLE chat_messages (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	room_id VARCHAR(36) NOT NULL,
	sender_id VARCHAR(36) NOT NULL,
	message VARCHAR(4000) NOT NULL,
	message_type VARCHAR(16) NOT NULL,
	timestamp TEXT NOT NULL,
	read_at TEXT,
	FOREIGN KEY(room_id) REFERENCES chat_rooms (id),
	FOREIGN KEY(sender_id) REFERENCES users (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE coscholastic_assessments (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	enrollment_id VARCHAR(36) NOT NULL,
	term VARCHAR(80) NOT NULL,
	areas TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY(enrollment_id) REFERENCES enrollments (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, enrollment_id, term)
);

CREATE TABLE fee_profiles (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	enrollment_id VARCHAR(36) NOT NULL,
	fee_structure_id VARCHAR(36) NOT NULL,
	FOREIGN KEY(enrollment_id) REFERENCES enrollments (id),
	FOREIGN KEY(fee_structure_id) REFERENCES fee_structures (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (enrollment_id)
);

CREATE TABLE notification_reads (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	notification_id VARCHAR(36) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	read_at TEXT NOT NULL,
	FOREIGN KEY(notification_id) REFERENCES notifications (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	PRIMARY KEY (id),
	UNIQUE (notification_id, user_id)
);

CREATE TABLE result_records (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	enrollment_id VARCHAR(36) NOT NULL,
	exam_type VARCHAR(80) NOT NULL,
	subject VARCHAR(120) NOT NULL,
	marks_obtained INTEGER NOT NULL,
	max_marks INTEGER NOT NULL,
	teacher_remarks VARCHAR(1000),
	entered_by VARCHAR(200) NOT NULL,
	is_published INTEGER NOT NULL,
	updated_at TEXT NOT NULL,
	voided_at TEXT,
	CONSTRAINT marks_obtained_scaled_integer CHECK (typeof(marks_obtained) = 'integer'),
	CONSTRAINT max_marks_scaled_integer CHECK (typeof(max_marks) = 'integer'),
	CONSTRAINT result_marks_nonnegative CHECK (marks_obtained >= 0),
	CONSTRAINT result_marks_within_max CHECK (marks_obtained <= max_marks),
	CONSTRAINT result_max_marks_positive CHECK (max_marks > 0),
	FOREIGN KEY(enrollment_id) REFERENCES enrollments (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, enrollment_id, exam_type, subject)
);

CREATE TABLE transport_assignments (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	student_id VARCHAR(36) NOT NULL,
	student_name VARCHAR(200) NOT NULL,
	class_name VARCHAR(80) NOT NULL,
	roll_number VARCHAR(32),
	bus_id VARCHAR(36) NOT NULL,
	route_id VARCHAR(36) NOT NULL,
	pickup_stop VARCHAR(200),
	status VARCHAR(16) NOT NULL,
	assigned_date TEXT NOT NULL,
	created_at TEXT NOT NULL,
	FOREIGN KEY(bus_id) REFERENCES buses (id),
	FOREIGN KEY(route_id) REFERENCES transport_routes (id),
	FOREIGN KEY(student_id) REFERENCES students (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id)
);

CREATE TABLE ai_usage (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	conversation_id VARCHAR(36),
	provider VARCHAR(32) NOT NULL,
	input_tokens INTEGER NOT NULL,
	output_tokens INTEGER NOT NULL,
	status VARCHAR(16) NOT NULL,
	request_timestamp TEXT NOT NULL,
	FOREIGN KEY(conversation_id) REFERENCES ai_conversations (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	PRIMARY KEY (id)
);

CREATE TABLE fee_installments (
	id VARCHAR(36) NOT NULL,
	profile_id VARCHAR(36) NOT NULL,
	position INTEGER NOT NULL,
	name VARCHAR(160) NOT NULL,
	amount_due INTEGER NOT NULL,
	paid_amount INTEGER NOT NULL,
	discount_amount INTEGER NOT NULL,
	status VARCHAR(16) NOT NULL,
	CONSTRAINT amount_due_scaled_integer CHECK (typeof(amount_due) = 'integer'),
	CONSTRAINT discount_amount_scaled_integer CHECK (typeof(discount_amount) = 'integer'),
	CONSTRAINT fee_installment_amount_nonnegative CHECK (amount_due >= 0),
	CONSTRAINT fee_installment_discount_nonnegative CHECK (discount_amount >= 0),
	CONSTRAINT fee_installment_not_overpaid CHECK (paid_amount + discount_amount <= amount_due),
	CONSTRAINT fee_installment_paid_nonnegative CHECK (paid_amount >= 0),
	CONSTRAINT paid_amount_scaled_integer CHECK (typeof(paid_amount) = 'integer'),
	FOREIGN KEY(profile_id) REFERENCES fee_profiles (id),
	PRIMARY KEY (id),
	UNIQUE (profile_id, name)
);

CREATE TABLE payments (
	id VARCHAR(36) NOT NULL,
	tenant_id VARCHAR(64) NOT NULL,
	profile_id VARCHAR(36) NOT NULL,
	receipt_number VARCHAR(64) NOT NULL,
	payment_date TEXT NOT NULL,
	amount_paid INTEGER NOT NULL,
	discount INTEGER NOT NULL,
	payment_mode VARCHAR(32) NOT NULL,
	transaction_reference VARCHAR(120),
	cheque_details VARCHAR(200),
	remarks VARCHAR(1000),
	idempotency_key VARCHAR(128),
	request_fingerprint VARCHAR(64),
	collected_by_user_id VARCHAR(36),
	student_name_snapshot VARCHAR(200),
	voided_at TEXT,
	void_reason VARCHAR(500),
	voided_by_user_id VARCHAR(36),
	CONSTRAINT amount_paid_scaled_integer CHECK (typeof(amount_paid) = 'integer'),
	CONSTRAINT discount_scaled_integer CHECK (typeof(discount) = 'integer'),
	CONSTRAINT fk_payments_collected_by_user_id_users FOREIGN KEY(collected_by_user_id) REFERENCES users (id),
	CONSTRAINT fk_payments_voided_by_user_id_users FOREIGN KEY(voided_by_user_id) REFERENCES users (id),
	CONSTRAINT payment_amount_nonnegative CHECK (amount_paid >= 0),
	CONSTRAINT payment_discount_nonnegative CHECK (discount >= 0),
	FOREIGN KEY(profile_id) REFERENCES fee_profiles (id),
	FOREIGN KEY(tenant_id) REFERENCES tenants (id),
	PRIMARY KEY (id),
	UNIQUE (tenant_id, idempotency_key),
	UNIQUE (tenant_id, payment_mode, transaction_reference),
	UNIQUE (tenant_id, receipt_number)
);

CREATE TABLE payment_allocations (
	id VARCHAR(36) NOT NULL,
	payment_id VARCHAR(36) NOT NULL,
	installment_id VARCHAR(36) NOT NULL,
	position INTEGER NOT NULL,
	amount_paid INTEGER NOT NULL,
	discount INTEGER NOT NULL,
	CONSTRAINT allocation_amount_nonnegative CHECK (amount_paid >= 0),
	CONSTRAINT allocation_discount_nonnegative CHECK (discount >= 0),
	CONSTRAINT amount_paid_scaled_integer CHECK (typeof(amount_paid) = 'integer'),
	CONSTRAINT discount_scaled_integer CHECK (typeof(discount) = 'integer'),
	FOREIGN KEY(installment_id) REFERENCES fee_installments (id),
	FOREIGN KEY(payment_id) REFERENCES payments (id),
	PRIMARY KEY (id),
	UNIQUE (payment_id, installment_id)
);

CREATE INDEX ix_academic_years_tenant_id ON academic_years (tenant_id);

CREATE INDEX ix_class_subjects_tenant_id ON class_subjects (tenant_id);

CREATE INDEX ix_contact_enquiries_tenant_id ON contact_enquiries (tenant_id);

CREATE INDEX ix_exam_configs_tenant_id ON exam_configs (tenant_id);

CREATE INDEX ix_expenses_tenant_id ON expenses (tenant_id);

CREATE INDEX ix_fee_structures_tenant_id ON fee_structures (tenant_id);

CREATE INDEX ix_rollover_runs_tenant_id ON rollover_runs (tenant_id);

CREATE INDEX ix_school_classes_tenant_id ON school_classes (tenant_id);

CREATE INDEX ix_school_subjects_tenant_id ON school_subjects (tenant_id);

CREATE INDEX ix_staff_tenant_id ON staff (tenant_id);

CREATE INDEX ix_students_tenant_id ON students (tenant_id);

CREATE INDEX ix_timetable_days_tenant_id ON timetable_days (tenant_id);

CREATE INDEX ix_transport_routes_tenant_id ON transport_routes (tenant_id);

CREATE INDEX ix_users_scope ON users (scope);

CREATE INDEX ix_auth_sessions_user_id ON auth_sessions (user_id);

CREATE INDEX ix_buses_tenant_id ON buses (tenant_id);

CREATE INDEX ix_certificate_records_student_id ON certificate_records (student_id);

CREATE INDEX ix_certificate_records_tenant_id ON certificate_records (tenant_id);

CREATE INDEX ix_chat_rooms_participant_1_id ON chat_rooms (participant_1_id);

CREATE INDEX ix_chat_rooms_participant_2_id ON chat_rooms (participant_2_id);

CREATE INDEX ix_chat_rooms_tenant_id ON chat_rooms (tenant_id);

CREATE INDEX ix_class_year_closures_tenant_id ON class_year_closures (tenant_id);

CREATE INDEX ix_enrollments_student_id ON enrollments (student_id);

CREATE INDEX ix_enrollments_tenant_id ON enrollments (tenant_id);

CREATE INDEX ix_homework_tenant_id ON homework (tenant_id);

CREATE INDEX ix_incidents_student_id ON incidents (student_id);

CREATE INDEX ix_incidents_tenant_id ON incidents (tenant_id);

CREATE INDEX ix_leave_requests_staff_id ON leave_requests (staff_id);

CREATE INDEX ix_leave_requests_tenant_id ON leave_requests (tenant_id);

CREATE INDEX ix_notifications_tenant_id ON notifications (tenant_id);

CREATE INDEX ix_salary_records_staff_id ON salary_records (staff_id);

CREATE INDEX ix_salary_records_tenant_id ON salary_records (tenant_id);

CREATE INDEX ix_staff_attendance_staff_id ON staff_attendance (staff_id);

CREATE INDEX ix_staff_attendance_tenant_id ON staff_attendance (tenant_id);

CREATE INDEX ix_timetable_periods_day_id ON timetable_periods (day_id);

CREATE INDEX ix_tutorial_videos_tenant_id ON tutorial_videos (tenant_id);

CREATE INDEX ix_ai_conversations_tenant_id ON ai_conversations (tenant_id);

CREATE INDEX ix_ai_conversations_user_id ON ai_conversations (user_id);

CREATE INDEX ix_attendance_enrollment_id ON attendance (enrollment_id);

CREATE INDEX ix_attendance_tenant_id ON attendance (tenant_id);

CREATE INDEX ix_chat_messages_room_id ON chat_messages (room_id);

CREATE INDEX ix_chat_messages_sender_id ON chat_messages (sender_id);

CREATE INDEX ix_chat_messages_tenant_id ON chat_messages (tenant_id);

CREATE INDEX ix_coscholastic_assessments_enrollment_id ON coscholastic_assessments (enrollment_id);

CREATE INDEX ix_coscholastic_assessments_tenant_id ON coscholastic_assessments (tenant_id);

CREATE INDEX ix_fee_profiles_tenant_id ON fee_profiles (tenant_id);

CREATE INDEX ix_notification_reads_notification_id ON notification_reads (notification_id);

CREATE INDEX ix_notification_reads_tenant_id ON notification_reads (tenant_id);

CREATE INDEX ix_notification_reads_user_id ON notification_reads (user_id);

CREATE INDEX ix_result_records_enrollment_id ON result_records (enrollment_id);

CREATE INDEX ix_result_records_tenant_id ON result_records (tenant_id);

CREATE INDEX ix_transport_assignments_bus_id ON transport_assignments (bus_id);

CREATE INDEX ix_transport_assignments_route_id ON transport_assignments (route_id);

CREATE INDEX ix_transport_assignments_student_id ON transport_assignments (student_id);

CREATE INDEX ix_transport_assignments_tenant_id ON transport_assignments (tenant_id);

CREATE UNIQUE INDEX uq_transport_active_student ON transport_assignments (tenant_id, student_id) WHERE status = 'ACTIVE';

CREATE INDEX ix_ai_usage_tenant_id ON ai_usage (tenant_id);

CREATE INDEX ix_ai_usage_user_id ON ai_usage (user_id);

CREATE INDEX ix_payments_profile_id ON payments (profile_id);

CREATE INDEX ix_payments_tenant_id ON payments (tenant_id);

CREATE INDEX ix_payment_allocations_payment_id ON payment_allocations (payment_id);

INSERT INTO schema_versions (version, applied_at) VALUES ('0002_school_schema', CURRENT_TIMESTAMP);
